name: Push Docker Image

on:
  push:
    branches: [ main ]
    
jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest

    env:
      IMAGE: namelessrealms-daedalus
  
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: get-package-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@v1.3.1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to private registry
      uses: docker/login-action@v3
      with:
        registry: namelessrealms.com
        username: ${{ secrets.MCKISMETLAB_DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.MCKISMETLAB_DOCKER_REGISTRY_PASSWORD }}

    - name: Build the Docker image And Push
      id: firs-docker-pull
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_STORAGE_IP }}/${{ env.IMAGE }}:latest
#         ${{ secrets.DOCKER_STORAGE_IP }}/${{ env.IMAGE }}:${{ steps.package-version.outputs.current-version}}
      continue-on-error: true

    - name: Retry again on failure Build the Docker image And Push
      id: second-docker-pull
      if: steps.firs-docker-pull.outcome != 'success'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_STORAGE_IP }}/${{ env.IMAGE }}:latest
#         ${{ secrets.DOCKER_STORAGE_IP }}/${{ env.IMAGE }}:${{ steps.package-version.outputs.current-version}}

#    - name: Invoke deployment hook
#      uses: distributhor/workflow-webhook@v2
#      env:
#        webhook_url: ${{ secrets.WEBHOOK_URL }}/mkl-api-build-webhook
#        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
#        webhook_auth: ${{ secrets.WEBHOOK_USERNAME }}:${{ secrets.WEBHOOK_PASSWORD }}
